name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
jobs:
  postgres:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.0', '3.1']
        gemfile:
          - rails_7
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports: ['5432:5432']
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true
          rubygems: "3.4.4"
      - name: StandardRb check
        run: |
          bundle exec standardrb -v
          bundle exec standardrb
      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/test
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
          PG_USER: postgres
          HOOK_RELAY_API_KEY: "${{secrets.HOOK_RELAY_API_KEY}}"
          HOOK_RELAY_ACCOUNT_ID: "${{secrets.HOOK_RELAY_ACCOUNT_ID}}"
          HOOK_RELAY_HOOK_ID: "${{secrets.HOOK_RELAY_HOOK_ID}}"
        run: |
          bin/rails db:test:prepare
          bin/rails test