name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
jobs:
  postgres:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.0']
        gemfile:
          - rails_7
          - rails_master
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        ports: ['5432:5432']

    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true
      - name: StandardRb check
        run: bundle exec standardrb
      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/test
        run: |
          bin/rails db:test:prepare
          bin/rails test